### ISSUE TITLE
CI based on unsupported Node.js 12

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/docker-image-not-found#2]
## Issue

The [CircleCI workflow](https://github.com/cypress-io/docker-image-not-found/blob/master/circle.yml) uses the CircleCI executor

```yaml
jobs:
  build:
    executor:
      name: node/default
      tag: '12'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run lint
      - run: npm test
```

and

```yaml
orbs:
  node: circleci/node@1.1
version: 2.1
```

This references the deprecated Docker image `circleci/node:12` using Node.js `12.22.7`

Node.js `12` entered [end-of-life](https://github.com/nodejs/Release/blob/main/README.md) in April 2022.
